import fetch from 'node-fetch'
let handler = async (m, { conn }) => {
  let caption =  `
╭─[𝐒𝐔𝐏𝐄𝐑 𝐁𝐎𝐓]───╮
 | 
│╭────────────────────
┴│👋 Hey there, ${conn.getName(m.sender)}!
⬡│🤖 I\'m 𝐒𝐔𝐏𝐄𝐑 𝐁𝐎𝐓\n⬡│ I\'m up and running! 🚀
│╰────────────────────
┠───[ *BOT INFO* ]────╮
│╭────────────────────
┴│    𝐒𝐔𝐏𝐄𝐑 𝐁𝐎𝐓
⬡│💻 A WhatsApp bot created by:
⬡│👨‍💻 𝐉𝐀𝐘𝐃𝐄𝐍
⬡│📞 For any inquiries, contact:
⬡│📱 wa.me/254794597254
⬡│🙅‍♂️ Don't call the owner or you\'ll be
⬡│ ignored or blocked! 😬
│╰────────────────────
┠───[ *HOW TO USE* ]────⋆
┴│💡 *Some commands you can use:*
⬡│🔸 .menu \n⬡│- Shows a list of available commands
⬡│🔸 .play \n⬡│- Plays a YouTube video or audio.
⬡│🔸 .sticker \n⬡│- Converts an image to a sticker
┬│🔸 .Ai text \n⬡│- Artificial intelligence 
││ https://github.com/K/jayden-official
│╰──────────────
╰────────═┅═───────
*Generated by *𝐒𝐔𝐏𝐄𝐑 𝐁𝐎𝐓*
`.trim()
conn.sendMessage(m.chat, { image: { url: 'https://telegra.ph/file/b1ed0e3edea657d1a255b.jpg' }, caption: caption, footer: `Follow me on instagram:\n\tinstagram.com/itx_ahmad.ali` }, { quoted: m })
  //m.reply(caption)
}
handler.help = ['alive']
handler.tags = ['bot check']
handler.command = /^(alive|Hi)$/i


export default handler
