import fetch from 'node-fetch'
let handler = async (m, { conn }) => {
  let caption =  `
╭─[𝐒𝐔𝐏𝐄𝐑 𝐁𝐎𝐓]───╮
 | 
│╭────────────────────
┴│👋 Hey there, ${conn.getName(m.sender)}!
⬡│🤖 I\'m 𝐒𝐔𝐏𝐄𝐑 𝐁𝐎𝐓\n⬡│ I\'m up and running! 🚀
│╰────────────────────
┠───[ *BOT INFO* ]────╮
│╭────────────────────
┴│    𝐒𝐔𝐏𝐄𝐑 𝐁𝐎𝐓
⬡│💻 A WhatsApp bot created by:
⬡│👨‍💻 𝐉𝐀𝐘𝐃𝐄𝐍
⬡│📞 For any inquiries, contact:
⬡│📱 wa.me/254794597254
💛🚦 wa.me/254796283064
⬡│🙅‍♂️ Don't call the owner or you'll be
⬡│ ignored or blocked motherfucker😂🖕
││ https://whatsapp.com/channel/0029Vag3MeuGJP8LZb1Okj39
*Generated by *☸️𝔠𝔬𝔫𝔣𝔯𝔬𝔫𝔱𝔢𝔯☸️*
`.trim()
conn.sendMessage(m.chat, { image: { url: 'https://telegra.ph/file/cbf9fca4824f1778a8466.jpg' }, caption: caption, footer: `Follow me on instagram:\n\tinstagram.com/itx_ahmad.ali` }, { quoted: m })
  //m.reply(caption)
}
handler.help = ['alive']
handler.tags = ['bot check']
handler.command = /^(alive|Hi)$/i


export default handler
